s1='NitiAayog'
s2='And Quit Flows The Don'
s3='1234567890'
s4='Make $1000 a day'
print('s1=',s1)
print('s2=',s2)
print('s3=',s3)
print('s4=',s4)
print()
print('check is alpha on all')
print(s1.isalpha())
print(s2.isalpha())
print(s3.isalpha())
print(s4.isalpha())
print()
print('isdigit on all')
print(s1.isdigit())
print(s2.isdigit())
print(s3.isdigit())
print(s4.isdigit())
print()
print('isalnum on all')
print(s1.isalnum())
print(s2.isalnum())
print(s3.isalnum())
print(s4.isalnum())
print()
print('islower on all')
print(s1.islower())
print(s2.islower())
print(s3.islower())
print(s4.islower())
print()
print('isupper on all')
print(s1.isupper())
print(s2.isupper())
print(s3.isupper())
print(s4.isupper())
print()
print('startswith and endswith on s2')
print(s2.startswith('And'))
print(s2.endswith('And'))
print('-'*45)
print(s2.istitle())