x='vishnu'
print(x[0])
print(x[-1])
print(x[0:2])
print(x[0:200])
print(x[:2])
print(x[:])
print(x[5:])
print(x[0:2:1])
print(x[0:5:2])
print(x[0:2:-1])
print(x[0:2:-2])
print(x[-5:3:1])
#print(x[500])
print('-',50)
print('-'*50)
print('v' in 'vishnu')
print('hn' in 'vishnu')
print(min('vishnu'))
print(max('vishnu'))
print(len('vishnu'))
print(('vishnu').lower())
print(('vishnu').upper())
print(('vishnu').isupper())
print(('vishnu').islower())
print(('vishnu').isalpha())
print(('vishnu').isdigit())
print(('vishnu').isalnum())
print(('vishnu').startswith('vis'))
print(('vishnu').startswith('v'))
print(('vishnu').endswith('u'))
print(('vishnu').endswith('nu'))
print(('vishnu').find('nu'))
print(('vishnu').find('nx'))
print(('vishnu').join('-'))
print(('v i s h n u').split(' '))
print(('vishnu').split('h'))
print(('vishnu').partition('h'))
print(('v\\i\\s\\h\\n\\u').partition('\\'))
print(('v\\i\\s\\h\\n\\u').split('\\'))
print(('vi s hnu').partition(' '))
print(('vishnu').replace('nu','NU'))
print(('  vis  hnu  ').lstrip())
print(('  vis  hnu  ').rstrip())
print(('  vis  hnu  ').strip())
print(type('vishnu'))
print(id('vishnu'))
print(('vishnu kumar').capitalize())
print(('vishnu kumar').title())
print(('Vishnu Kumar').swapcase())
print(('vishnu kumar').swapcase())
print(dir('str'))
print(chr(65))
print(ord('v'))