f=open('numbers.txt','wb')
f.write(b'231')
f.write(b'431')
f.write(b'2632')
f.write(b'833')
f.close()

f=open('numbers.txt','rb')
f.seek(10,0)
print(f.tell())
f.seek(2,1)
print(f.tell())
f.seek(-5,1)
print(f.tell())
f.seek(-10,2)
print(f.tell())